services:
  - type: web
    name: nlp-mindmaster
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://nlp-mindmaster2-1.onrender.com
      - key: LOG_CHANNEL
        value: stderr
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan storage:link
      php artisan optimize
    startCommand: apache2-foreground
